### ISSUE TITLE
What's format of channel topic?

### ISSUE THREAD

**Issue by wizicer** [ajmeese7/keybase-export#1]
I'd like to export conversation in channel topic, but seems the keybase api not work.

input is `username,chia_network.public#general`
error like this:
```json
{"error":{"code":0,"message":"bad keybase username 'chia_network.public': between 2 and 16 characters long"}}
```

I cannot find proper API doc for keybase, any suggestion is great appreciate.

**Comment by wizicer** [comment]
Found a workaround: using conversation_id instead.
```json
{"method": "read", "params": {"options": {"conversation_id": "0000f0e275093efa4408dd40xxxxxxxxxxxxxxxxxxxxxxxx2caa50d9998f30891855f6", "pagination": {"num": 1000}}}}
```

conversation_id can be retrieved by `keybase chat conv-info`

**Comment by ajmeese7** [comment]
Great, thanks for the contribution! I hope anyone else who encounters this problem comes across this issue and your solution.
